import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { poppins } from "./src/fonts";
import RootThemeProvider from "@/components/common/RootThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className={poppins.className}>
        <AppRouterCacheProvider>
          <RootThemeProvider>
            {children}
          </RootThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
